import { DIAGRAM_VERSION } from "../templates.js";

const edge = (source, target, label, targetPort = "in") => ({
  id: `${source}-${target}`,
  source,
  target,
  label,
  kind: "data",
  sourcePort: "out",
  targetPort,
});

export const clip = {
  id: "clip",
  title: "CLIP",
  checkpoint: "ViT-L/14",
  category: "Vision Encoders",
  number: "01",
  subtitle: "Dual encoders / shared embedding space",
  version: DIAGRAM_VERSION,
  evidence: "Source-verified architecture",
  description:
    "Independent image and text towers map both modalities into one embedding space. Their similarity scores support image-text retrieval and zero-shot classification.",
  note: "OpenAI ViT-L/14 at 224 px only. Encoder internals and the training loss are summarized in details. This is the original contrastive model, not an MLLM adapter or a generative decoder.",
  notation: [
    ["B / K", "Image / text batch size"],
    ["I / T", "Unit-length image / text vectors"],
    ["s", "Learned logit-scale parameter"],
  ],
  stages: ["Input", "Encode", "Project", "Normalize", "Match"],
  nodes: [
    {
      id: "image",
      kind: "input",
      label: "Image",
      subtitle: "Visual input",
      column: 0,
      row: 0,
      symbol: "image",
      input: "B images",
      output: "B x 3 x 224 x 224",
      description:
        "Inference preprocessing resizes, center-crops, converts to RGB, and applies CLIP channel normalization.",
      properties: [
        ["Resolution", "224 x 224"],
        ["Channels", "3 / RGB"],
        ["Resize", "Bicubic"],
      ],
    },
    {
      id: "vision-encoder",
      kind: "operation",
      label: "Image encoder",
      subtitle: "Vision transformer",
      column: 1,
      row: 0,
      symbol: "layers",
      input: "B x 3 x 224 x 224",
      output: "B x 1024",
      description:
        "The vision tower contextualizes patch tokens and returns the normalized class-token representation before projection.",
      properties: [
        ["Backbone", "ViT-L/14"],
        ["Patch size", "14 x 14"],
        ["Sequence", "256 patches + CLS"],
        ["Transformer layers", "24"],
        ["Hidden width", "1024"],
        ["Attention heads", "16 / bidirectional"],
        ["MLP width", "4096 / QuickGELU"],
        ["Readout", "CLS + LayerNorm"],
      ],
      steps: [
        "14 x 14 patch embedding",
        "Class + position embeddings",
        "Pre-LN + 24 vision blocks",
        "CLS selection + LayerNorm",
      ],
    },
    {
      id: "image-projection",
      kind: "operation",
      label: "Image projection",
      subtitle: "Linear mapping",
      column: 2,
      row: 0,
      symbol: "projector",
      input: "B x 1024",
      output: "B x 768",
      description:
        "A learned linear map projects image features into the shared space.",
      properties: [
        ["Weight shape", "1024 x 768"],
        ["Bias", "None"],
        ["Nonlinearity", "None"],
      ],
    },
    {
      id: "image-embedding",
      kind: "operation",
      label: "Image embedding",
      subtitle: "L2 normalization",
      column: 3,
      row: 0,
      symbol: "norm",
      input: "B x 768",
      output: "I: B x 768",
      description: "Each projected image vector is divided by its L2 norm.",
      properties: [
        ["Embedding width", "768"],
        ["Vector norm", "1"],
      ],
    },
    {
      id: "similarity",
      kind: "output",
      label: "Similarity",
      subtitle: "Image-text scores",
      column: 4,
      row: 0,
      symbol: "matrix",
      input: "I: B x 768; T: K x 768",
      output: "B x K logits",
      description:
        "Pairwise cosine scores are multiplied by a learned positive scale. In training, matched image-text pairs form the diagonal of a square batch matrix; row and column cross-entropy losses are averaged.",
      properties: [
        ["Logits", "exp(s) * I @ T^T"],
        ["Scale", "Learned; not fixed at 100"],
        ["Training", "B = K; paired diagonal targets"],
        ["Objective", "Mean of image-to-text and text-to-image CE"],
        ["Inference", "B and K can differ"],
        ["Class scores", "Softmax over candidate texts"],
      ],
    },
    {
      id: "text",
      kind: "input",
      label: "Text",
      subtitle: "Caption or class prompt",
      column: 0,
      row: 1,
      symbol: "text",
      input: "K text strings",
      output: "K x 77 token IDs",
      description:
        "Byte-pair tokenization adds start/end tokens and pads to 77 positions. The official tokenizer rejects longer inputs unless truncation is explicitly enabled.",
      properties: [
        ["Tokenizer", "Byte-level BPE"],
        ["Vocabulary", "49,408"],
        ["Context", "77 positions including special tokens"],
      ],
    },
    {
      id: "text-encoder",
      kind: "operation",
      label: "Text encoder",
      subtitle: "Causal transformer",
      column: 1,
      row: 1,
      symbol: "layers",
      input: "K x 77 token IDs",
      output: "K x 768",
      description:
        "A separate causal transformer produces a text representation at the end-of-text token. It does not attend to image tokens.",
      properties: [
        ["Transformer layers", "12"],
        ["Hidden width", "768"],
        ["Attention heads", "12 / causal"],
        ["MLP width", "3072 / QuickGELU"],
        ["Readout", "LayerNorm + EOT selection"],
      ],
      steps: [
        "Token + position embeddings",
        "12 causal transformer blocks",
        "Final LayerNorm",
        "End-of-text selection",
      ],
    },
    {
      id: "text-projection",
      kind: "operation",
      label: "Text projection",
      subtitle: "Linear mapping",
      column: 2,
      row: 1,
      symbol: "projector",
      input: "K x 768",
      output: "K x 768",
      description:
        "A distinct learned projection aligns text features, even though its input and output widths match.",
      properties: [
        ["Weight shape", "768 x 768"],
        ["Weights", "Not shared with image projection"],
        ["Bias", "None"],
      ],
    },
    {
      id: "text-embedding",
      kind: "operation",
      label: "Text embedding",
      subtitle: "L2 normalization",
      column: 3,
      row: 1,
      symbol: "norm",
      input: "K x 768",
      output: "T: K x 768",
      description: "Each projected text vector is divided by its L2 norm.",
      properties: [
        ["Embedding width", "768"],
        ["Vector norm", "1"],
      ],
    },
  ],
  edges: [
    edge("image", "vision-encoder", "B x 3 x 224 x 224"),
    edge("vision-encoder", "image-projection", "B x 1024"),
    edge("image-projection", "image-embedding", "B x 768"),
    edge("image-embedding", "similarity", "I: B x 768"),
    edge("text", "text-encoder", "K x 77"),
    edge("text-encoder", "text-projection", "K x 768"),
    edge("text-projection", "text-embedding", "K x 768"),
    edge("text-embedding", "similarity", "T: K x 768", "aux"),
  ],
  sources: [
    {
      title: "CLIP paper",
      url: "https://proceedings.mlr.press/v139/radford21a/radford21a.pdf",
      location:
        "Sections 2.2-2.3; Figures 1 and 3: dual encoders and symmetric contrastive objective.",
    },
    {
      title: "Checkpoint dimensions",
      url: "https://proceedings.mlr.press/v139/radford21a/radford21a-supp.pdf#page=25",
      location:
        "Table 20, ViT-L/14 row: 224 px, vision 24/1024/16, text 12/768/12, shared width 768.",
    },
    {
      title: "OpenAI model implementation",
      url: "https://github.com/openai/CLIP/blob/main/clip/model.py",
      location:
        "VisionTransformer.forward, CLIP.encode_text and CLIP.forward: readouts, projections, normalization and logits.",
    },
    {
      title: "OpenAI preprocessing",
      url: "https://github.com/openai/CLIP/blob/main/clip/clip.py",
      location:
        "_transform and tokenize: image preprocessing and 77-position text context.",
    },
    {
      title: "ViT-L/14 configuration",
      url: "https://huggingface.co/openai/clip-vit-large-patch14/blob/main/config.json",
      location:
        "OpenAI checkpoint: vision/text widths, layers, heads, MLP dimensions and projection dimension.",
    },
  ],
};
